In [10]:
   # =====================================================
# ASSIGNMENT 10 - Data Analytics III
# Naive Bayes Classification on Iris Dataset
# =====================================================

# STEP 1: Imports (only needed!)
import seaborn as sns
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.preprocessing import LabelEncoder      

In [3]:
# STEP 2: Load Dataset (built-in!)
df = sns.load_dataset('iris')
print("Dataset Loaded!")
print(df.head())

Dataset Loaded!
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [18]:
# STEP 3: X and Y
X = df.drop('species', axis=1)   # 4 features
Y = df['species']                 # species name

# Convert species text to numbers (setosa=0, versicolor=1, virginica=2)
le = LabelEncoder()
Y = le.fit_transform(Y)
print(le.classes_)

['setosa' 'versicolor' 'virginica']


In [5]:
# STEP 4: Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [6]:
    # STEP 5: Train Naive Bayes Model
model = GaussianNB()
model.fit(X_train, Y_train)
print("\nModel Trained!")

# STEP 6: Predict
Y_pred = model.predict(X_test)
print("Predictions:", Y_pred)
print("Actual     :", Y_test)


Model Trained!
Predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Actual     : [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [11]:
mcm = multilabel_confusion_matrix(Y_test, Y_pred)
print("\nmultilabel Confusion Matrix:")
print(mcm)


multilabel Confusion Matrix:
[[[20  0]
  [ 0 10]]

 [[21  0]
  [ 0  9]]

 [[19  0]
  [ 0 11]]]


In [20]:

# Ek line mein saare classes ka TP/TN/FP/FN!
mcm = multilabel_confusion_matrix(Y_test, Y_pred)

# classes = ['setosa', 'versicolor', 'virginica']

for i in range(3):
    TN = mcm[i][0][0]
    FP = mcm[i][0][1]
    FN = mcm[i][1][0]
    TP = mcm[i][1][1]

    accuracy  = (TP + TN) / (TP + TN + FP + FN)
    error     = 1 - accuracy
    precision = TP / (TP + FP)
    recall    = TP / (TP + FN)

    print("\nClass:", le.classes_[i])
    print("  TP:", TP, " TN:", TN, " FP:", FP, " FN:", FN)
    print("  Accuracy :", round(accuracy, 2))
    print("  Error    :", round(error, 2))
    print("  Precision:", round(precision, 2))
    print("  Recall   :", round(recall, 2))


Class: setosa
  TP: 10  TN: 20  FP: 0  FN: 0
  Accuracy : 1.0
  Error    : 0.0
  Precision: 1.0
  Recall   : 1.0

Class: versicolor
  TP: 9  TN: 21  FP: 0  FN: 0
  Accuracy : 1.0
  Error    : 0.0
  Precision: 1.0
  Recall   : 1.0

Class: virginica
  TP: 11  TN: 19  FP: 0  FN: 0
  Accuracy : 1.0
  Error    : 0.0
  Precision: 1.0
  Recall   : 1.0
